const countryFacts = {
  "Afghanistan": "Afghanistan has been continuously inhabited for over 50,000 years, making it one of the oldest human settlements on Earth.",
  "Albania": "Albania has more bunkers per square mile than any other country — over 170,000 built during the communist era.",
  "Algeria": "Algeria is the largest country in Africa by area, bigger than all of Western Europe combined.",
  "Argentina": "Argentina has the highest number of psychologists per capita in the world.",
  "Australia": "Australia has more than 10,000 beaches — enough to visit a new one every day for 27 years.",
  "Austria": "Austria is the birthplace of Mozart, Freud, and Schrödinger — and also the croissant.",
  "Andorra": "Andorra is a microstate between France and Spain with no airport, no army, and no national debt.",
  "Bangladesh": "Bangladesh is home to the Sundarbans, the world's largest mangrove forest, shared with India.",
  "Bhutan": "Bhutan is the only country in the world that measures success by Gross National Happiness instead of GDP.",
  "Belgium": "Belgium has more comic book artists per square kilometer than any other country.",
  "Bolivia": "Bolivia has two capital cities — Sucre is the constitutional capital, La Paz is the seat of government.",
  "Brunei": "Brunei is one of the few absolute monarchies in the world and has no income tax.",
  "Brazil": "Brazil is the only country in the Americas where Portuguese is the official language.",
  "Burkina Faso": "Burkina Faso means 'Land of Honest People' in the Mossi and Dioula languages.",
  "Cambodia": "Angkor Wat in Cambodia is the largest religious monument in the world, covering over 400 acres.",
  "Canada": "Canada has the longest coastline of any country in the world at over 200,000 km.",
  "Cape Verde": "Cape Verde was uninhabited until Portuguese explorers arrived in 1456.",
  "Chile": "Chile is the longest country in the world from north to south, stretching over 4,300 km.",
  "China": "China is home to the world's largest standing army with over 2 million active personnel.",
  "Comoros": "Comoros is the world's largest producer of ylang-ylang, used in high-end perfumes.",
  "Colombia": "Colombia is the only country in South America with coastlines on both the Pacific Ocean and the Caribbean Sea.",
  "Croatia": "Croatia has over 1,200 islands along its Adriatic coastline, though only about 50 are inhabited.",
  "Cuba": "Cuba has one of the highest literacy rates in the world at over 99%.",
  "Czech Republic": "The Czech Republic has the highest beer consumption per capita in the world.",
  "Denmark": "Denmark is consistently ranked as one of the happiest countries in the world.",
  "Djibouti": "Djibouti is home to Lake Assal, the saltiest lake outside Antarctica and the lowest point in Africa.",
  "Ecuador": "Ecuador was the first country in the world to give nature constitutional rights.",
  "Egypt": "Egypt is home to the only remaining wonder of the ancient world — the Great Pyramid of Giza.",
  "Eritrea": "Eritrea only gained independence from Ethiopia in 1993 after a 30-year war.",
  "Eswatini": "Eswatini is one of the world's last remaining absolute monarchies and changed its name from Swaziland in 2018.",
  "Ethiopia": "Ethiopia follows its own calendar, which is about 7 years behind the Gregorian calendar.",
  "Finland": "Finland has more saunas than cars — roughly 3.3 million saunas for 5.5 million people.",
  "Fiji": "Fiji is made up of 333 islands, of which only 110 are inhabited.",
  "France": "France is the most visited country in the world, welcoming nearly 90 million tourists per year.",
  "Gabon": "Gabon has over 80% forest cover and is one of the most carbon-negative countries on Earth.",
  "Gambia": "Gambia is the smallest country on mainland Africa, a thin strip of land almost entirely surrounded by Senegal.",
  "Germany": "Germany has over 1,500 different types of beer and around 1,300 breweries.",
  "Ghana": "Ghana was the first sub-Saharan African country to gain independence, in 1957.",
  "Greece": "Greece has more archaeological museums than any other country in the world.",
  "Guinea": "Guinea holds nearly half of the world's reserves of bauxite, the primary ore for aluminum.",
  "Guinea-Bissau": "Guinea-Bissau is an archipelago nation with over 88 islands off its coast.",
  "Guyana": "Guyana is the only English-speaking country in South America.",
  "Guatemala": "Guatemala is home to Lake Atitlán, described by Aldous Huxley as the most beautiful lake in the world.",
  "Haiti": "Haiti was the first Black republic in the world and the first Caribbean nation to gain independence, in 1804.",
  "Hungary": "Hungary has won more Olympic gold medals per capita than almost any other nation.",
  "Iceland": "Iceland has no army and has been at peace since 1944. It also has no mosquitoes.",
  "India": "India is the world's largest democracy with over 900 million eligible voters.",
  "Indonesia": "Indonesia is an archipelago of over 17,000 islands, making it the world's largest island nation.",
  "Iran": "Iran is one of the world's oldest civilizations, with a history spanning over 7,000 years.",
  "Iraq": "Iraq is home to Mesopotamia, widely considered the cradle of civilization.",
  "Ireland": "Ireland is the only country in the world where the national instrument is a harp.",
  "Israel": "Israel has the highest number of museums per capita in the world.",
  "Italy": "Italy has more UNESCO World Heritage Sites than any other country in the world.",
  "Jamaica": "Jamaica is the birthplace of reggae music and the Rastafari movement.",
  "Japan": "Japan has around 6,800 islands and over 1,500 earthquakes per year.",
  "Jordan": "Jordan's Dead Sea is the lowest point on Earth's surface at 430 meters below sea level.",
  "Kazakhstan": "Kazakhstan is the world's largest landlocked country, covering about the size of Western Europe.",
  "Kenya": "Kenya is home to the Great Rift Valley, one of the most significant geological features on Earth.",
  "Kosovo": "Kosovo declared independence in 2008 and is one of the youngest countries in the world.",
  "Kyrgyzstan": "Kyrgyzstan is home to one of the world's largest walnut forests, said to be 2,000 years old.",
  "Laos": "Laos is the most heavily bombed country per capita in history, from the Vietnam War era.",
  "Lebanon": "Lebanon is one of the smallest countries in the world but has 18 officially recognized religious sects.",
  "Lesotho": "Lesotho is one of only three countries in the world entirely surrounded by another country — South Africa.",
  "Liberia": "Liberia was founded in 1847 by freed American slaves and is Africa's oldest republic.",
  "Liechtenstein": "Liechtenstein is one of only two doubly landlocked countries in the world, along with Uzbekistan.",
  "Libya": "About 90% of Libya is covered by desert, primarily the Sahara.",
  "Luxembourg": "Luxembourg has the highest GDP per capita in the world.",
  "Madagascar": "Over 90% of Madagascar's wildlife is found nowhere else on Earth.",
  "Malaysia": "Malaysia is one of the world's top exporters of palm oil, rubber, and tin.",
  "Maldives": "The Maldives is the world's lowest-lying country, with an average ground level of just 1.5 meters above sea level.",
  "Mali": "Mali is home to Timbuktu, a legendary city that was once one of the world's most important centers of Islamic learning.",
  "Malta": "Malta is one of the world's most densely populated countries and has been inhabited for over 7,000 years.",
  "Marshall Islands": "The Marshall Islands were the site of 67 US nuclear weapons tests between 1946 and 1958.",
  "Mauritania": "Mauritania was the last country in the world to officially abolish slavery, in 1981.",
  "Mauritius": "Mauritius was the only known home of the dodo bird before it went extinct in the 17th century.",
  "Mexico": "Mexico City is sinking at a rate of about 50cm per year due to over-extraction of groundwater.",
  "Micronesia": "Micronesia is spread across 607 islands in the western Pacific Ocean.",
  "Moldova": "Moldova is home to the world's largest wine cellar — Mileștii Mici — with over 200km of underground tunnels.",
  "Monaco": "Monaco is the world's second smallest country and the most densely populated.",
  "Mongolia": "Mongolia has the lowest population density of any country in the world.",
  "Montenegro": "Montenegro means 'Black Mountain' in the local language.",
  "Morocco": "Morocco is home to the world's oldest continuously operating university — the University of al-Qarawiyyin, founded in 859 AD.",
  "Mozambique": "Mozambique's flag is the only national flag in the world that features a modern rifle.",
  "Myanmar": "Myanmar has over 2,000 temples in the ancient city of Bagan.",
  "Namibia": "Namibia was the first country in the world to incorporate environmental protection into its constitution.",
  "Nauru": "Nauru is the world's smallest island nation and the third smallest country overall.",
  "Nepal": "Nepal is home to eight of the world's ten tallest mountains, including Everest.",
  "Netherlands": "The Netherlands has more bicycles than people — about 23 million bikes for 17 million residents.",
  "Niger": "Niger is the largest country in West Africa but over 80% of its land is covered by the Sahara Desert.",
  "New Zealand": "New Zealand was the first country to give women the right to vote, in 1893.",
  "Nigeria": "Nigeria is Africa's most populous country with over 220 million people and 500+ languages spoken.",
  "North Macedonia": "North Macedonia is home to Lake Ohrid, one of the oldest lakes in the world at over 3 million years old.",
  "North Korea": "North Korea and Finland are both located on the same latitude as Alaska.",
  "Norway": "Norway has the world's longest road tunnel at 24.5 km — the Lærdal Tunnel.",
  "Pakistan": "Pakistan is home to K2, the world's second highest mountain and considered harder to climb than Everest.",
  "Palau": "Palau created the world's first shark sanctuary in 2009.",
  "Palestine": "Palestine is home to Jericho, one of the oldest continuously inhabited cities in the world.",
  "Panama": "The Panama Canal saves ships about 7,800 miles compared to sailing around South America.",
  "Paraguay": "Paraguay is one of only two landlocked countries in South America.",
  "Papua New Guinea": "Papua New Guinea has over 800 languages — more than any other country on Earth.",
  "Peru": "Peru is home to Machu Picchu, built by the Inca Empire at an altitude of 2,430 meters.",
  "Philippines": "The Philippines is an archipelago of over 7,600 islands with 180 languages spoken.",
  "Poland": "Poland has produced more Nobel Prize winners in literature per capita than almost any other country.",
  "Portugal": "Portugal is the world's oldest nation-state, with borders largely unchanged since 1139.",
  "Qatar": "Qatar has the highest GDP per capita in the Arab world and was the first Middle Eastern country to host the FIFA World Cup.",
  "Romania": "Romania is home to Dracula's Castle — Bran Castle in Transylvania.",
  "Russia": "Russia spans 11 time zones and is larger than the entire surface area of Pluto.",
  "Rwanda": "Rwanda is known as the 'Land of a Thousand Hills' and has one of the highest percentages of women in parliament.",
  "Saudi Arabia": "Saudi Arabia is the largest country in the world with no rivers.",
  "Samoa": "Samoa was the first Pacific Island nation to gain independence, in 1962.",
  "San Marino": "San Marino claims to be the world's oldest republic, founded in 301 AD.",
  "Senegal": "Senegal has never had a coup d'état, making it one of Africa's most stable democracies.",
  "Serbia": "Serbia is the world's largest exporter of raspberries, producing about 30% of the global supply.",
  "Sierra Leone": "Sierra Leone has one of the world's largest natural harbors in its capital, Freetown.",
  "Singapore": "Singapore is one of only three city-states in the world and has no natural freshwater lakes.",
  "Slovakia": "Slovakia has the highest number of castles and chateaux per capita in the world.",
  "Slovenia": "Slovenia is one of the few countries in the world where beekeeping is considered a national tradition.",
  "Somalia": "Somalia has the longest coastline of any country in mainland Africa.",
  "Solomon Islands": "The Solomon Islands were the site of some of the fiercest naval battles of World War II.",
  "South Africa": "South Africa has three capital cities — Pretoria, Cape Town, and Bloemfontein.",
  "South Sudan": "South Sudan is the world's newest country, having gained independence from Sudan in 2011.",
  "South Korea": "South Korea has the fastest average internet speed in the world.",
  "Spain": "Spain is the second largest country in the European Union by area.",
  "São Tomé and Príncipe": "São Tomé and Príncipe sits almost exactly on the equator and was uninhabited when Portuguese explorers arrived.",
  "Sri Lanka": "Sri Lanka was the first country in the world to elect a female head of government, in 1960.",
  "Sudan": "Sudan has more ancient pyramids than Egypt — over 200 compared to Egypt's 138.",
  "Suriname": "Suriname is the smallest sovereign state in South America and the only Dutch-speaking country on the continent.",
  "Sweden": "Sweden invented the safety match, the adjustable wrench, and the zipper.",
  "Switzerland": "Switzerland has enough nuclear bunkers to shelter its entire population.",
  "Syria": "Damascus, Syria, is one of the oldest continuously inhabited cities in the world.",
  "Tajikistan": "Over 90% of Tajikistan is covered by mountains, making it the most mountainous country in Central Asia.",
  "Taiwan": "Taiwan is the world's largest producer of computer chips.",
  "Tanzania": "Tanzania is home to Mount Kilimanjaro, the highest peak in Africa at 5,895 meters.",
  "Thailand": "Thailand is the world's largest exporter of rice and rubber.",
  "Timor-Leste": "Timor-Leste, also known as East Timor, only gained independence in 2002 making it one of the world's youngest nations.",
  "Togo": "Togo is one of the narrowest countries in the world, only 115km wide at its widest point.",
  "Tonga": "Tonga is the only Pacific nation never to have been colonized by a foreign power.",
  "Trinidad and Tobago": "Trinidad and Tobago is the birthplace of the steel pan, the only acoustic instrument invented in the 20th century.",
  "Tunisia": "Tunisia is where the original Star Wars desert scenes were filmed.",
  "Turkmenistan": "Turkmenistan has a gas crater known as the 'Door to Hell' that has been burning continuously since 1971.",
  "Turkey": "Turkey is home to the site of ancient Troy and has more ancient Greek ruins than Greece itself.",
  "Tuvalu": "Tuvalu is the world's fourth smallest country and may be the first nation submerged by rising sea levels.",
  "Uganda": "Uganda is home to half of the world's remaining mountain gorilla population.",
  "Ukraine": "Ukraine has the largest territory of any country entirely within Europe.",
  "United Kingdom": "The UK has not been successfully invaded since 1066.",
  "United States": "The US has the world's largest economy and the third largest population.",
  "Uruguay": "Uruguay was the first country in the world to fully legalize cannabis.",
  "Uzbekistan": "Uzbekistan is one of only two doubly landlocked countries in the world.",
  "Vanuatu": "Vanuatu consistently ranks as one of the happiest countries in the world despite being one of the least developed.",
  "Vatican City": "Vatican City is the world's smallest country at just 0.44 square kilometers.",
  "Venezuela": "Venezuela is home to Angel Falls, the world's highest uninterrupted waterfall at 979 meters.",
  "Vietnam": "Vietnam has the world's largest cave — Son Doong — big enough to have its own weather system.",
  "Western Sahara": "Western Sahara is one of the most sparsely populated territories on Earth.",
  "Yemen": "Yemen is home to Socotra Island, called the 'Galápagos of the Indian Ocean' for its unique wildlife.",
  "Zambia": "Zambia and Zimbabwe share Victoria Falls, one of the seven natural wonders of the world.",
  "Zimbabwe": "Zimbabwe once issued a 100 trillion dollar banknote during its hyperinflation crisis in 2008.",
};

export default countryFacts;